[package]
name = "tgbot-utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde_json = "1.0.94"
spdlog-rs = "0.3.8"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "sqlite", "offline"] }
teloxide = "0.12.2"
thiserror = "1.0.39"
tokio = "1.26.0"
url = "2.3.1"
